packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@parcel/watcher': set this to true or false

minimumReleaseAgeExclude:
  - vite
  - '@typescript'
  - lucide-react

overrides:
  lottie-web: '5.13.0'
