"""add more metadata

Revision ID: 62b7a4683d13
Revises: 6a8b2c4d1e3f
Create Date: 2026-07-31 14:45:22.782029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62b7a4683d13'
down_revision: Union[str, Sequence[str], None] = '6a8b2c4d1e3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    op.drop_index(op.f('idx_visit_browser_stats'), table_name='visitor_track')
    op.drop_index(op.f('idx_visit_os_stats'), table_name='visitor_track')
    op.drop_index(op.f('idx_visit_time_device_type'), table_name='visitor_track')
    op.drop_index(op.f('idx_visit_time_ip_address'), table_name='visitor_track')
    op.drop_index(op.f('idx_visit_time_page_path'), table_name='visitor_track')
    op.drop_index(op.f('idx_visit_time_visitor_id'), table_name='visitor_track')
    op.drop_index(op.f('ix_visitor_track_ip_address'), table_name='visitor_track')
    op.drop_index(op.f('ix_visitor_track_ipaddress'), table_name='visitor_track')
    op.drop_index(op.f('ix_visitor_track_visit_time'), table_name='visitor_track')
    op.drop_index(op.f('ix_visitor_track_visitor_id'), table_name='visitor_track')
    op.drop_index(op.f('ix_visitor_track_visitorid'), table_name='visitor_track')
    op.drop_index(op.f('ix_visitor_track_visittime'), table_name='visitor_track')
    op.drop_table('visitor_track')
    op.drop_index(op.f('ix_passkey_credentials_createdat'), table_name='passkey_credentials')
    op.drop_index(op.f('ix_passkey_credentials_userid'), table_name='passkey_credentials')
    op.drop_table('passkey_credentials')
    op.drop_index(op.f('ix_visitor_tracks_ipaddress'), table_name='visitor_tracks')
    op.drop_index(op.f('ix_visitor_tracks_visitorid'), table_name='visitor_tracks')
    op.drop_index(op.f('ix_visitor_tracks_visittime'), table_name='visitor_tracks')
    op.drop_table('visitor_tracks')
    op.drop_index(op.f('ix_rss_infos_createdat'), table_name='rss_infos')
    op.drop_index(op.f('ix_rss_infos_rssurl'), table_name='rss_infos')
    op.drop_index(op.f('ix_rss_infos_userid'), table_name='rss_infos')
    op.drop_table('rss_infos')
    op.drop_index(op.f('ix_device_tracks_createdat'), table_name='device_tracks')
    op.drop_index(op.f('ix_device_tracks_userid'), table_name='device_tracks')
    op.drop_table('device_tracks')
    op.drop_index(op.f('ix_logs_id'), table_name='logs')
    op.drop_index(op.f('ix_logs_level'), table_name='logs')
    op.drop_index(op.f('ix_logs_timestamp'), table_name='logs')
    op.drop_table('logs')
    op.drop_index(op.f('ix_gallery_images_createdat'), table_name='gallery_images')
    op.drop_index(op.f('ix_gallery_images_sortorder'), table_name='gallery_images')
    op.drop_index(op.f('ix_gallery_images_userid'), table_name='gallery_images')
    op.drop_table('gallery_images')
    op.drop_index(op.f('ix_subscriptions_createdat'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_userid'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.alter_column('device_track', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('device_track', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('device_track', 'purchase_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('device_track', 'price',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               nullable=False)
    op.alter_column('device_track', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('device_track', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('device_track', 'reminder_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_device_track_createdat'), table_name='device_track')
    op.drop_index(op.f('ix_device_track_userid'), table_name='device_track')
    op.alter_column('event', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('event', 'type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('event', 'source',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('event', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('event', 'message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('event', 'extra',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False)
    op.add_column('gallery_image', sa.Column('thumbnail_url', sa.String(length=500), nullable=True))
    op.add_column('gallery_image', sa.Column('medium_url', sa.String(length=500), nullable=True))
    op.add_column('gallery_image', sa.Column('width', sa.Integer(), nullable=False))
    op.add_column('gallery_image', sa.Column('height', sa.Integer(), nullable=False))
    op.add_column('gallery_image', sa.Column('aspect_ratio', sa.Float(), nullable=False))
    op.add_column('gallery_image', sa.Column('status', sa.String(length=20), nullable=False))
    op.alter_column('gallery_image', 'file_size',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('gallery_image', 'mime_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'image/jpeg'::character varying"))
    op.alter_column('gallery_image', 'description',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('gallery_image', 'sort_order',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('gallery_image', 'exif',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('gallery_image', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('gallery_image', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('gallery_image', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('gallery_image', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index(op.f('ix_gallery_image_createdat'), table_name='gallery_image')
    op.drop_index(op.f('ix_gallery_image_sortorder'), table_name='gallery_image')
    op.drop_index(op.f('ix_gallery_image_userid'), table_name='gallery_image')
    op.create_index(op.f('ix_gallery_image_status'), 'gallery_image', ['status'], unique=False)
    op.alter_column('log', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('log', 'level',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('log', 'message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('log', 'extra',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False)
    op.alter_column('passkey_credential', 'credential_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('passkey_credential', 'public_key',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('passkey_credential', 'sign_count',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('passkey_credential', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('passkey_credential', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.drop_index(op.f('ix_passkey_credential_createdat'), table_name='passkey_credential')
    op.drop_index(op.f('ix_passkey_credential_userid'), table_name='passkey_credential')
    op.drop_column('passkey_credential', 'attestation_format')
    op.drop_column('passkey_credential', 'backup_state')
    op.drop_column('passkey_credential', 'backup_eligible')
    op.alter_column('profile', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.drop_index(op.f('ix_profile_userid'), table_name='profile')
    op.create_unique_constraint(op.f('uq_profile_user_id'), 'profile', ['user_id'])
    op.alter_column('rss_info', 'rss_url',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('rss_info', 'entry_count',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('rss_info', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('rss_info', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('rss_info', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.drop_index(op.f('ix_rss_info_createdat'), table_name='rss_info')
    op.drop_index(op.f('ix_rss_info_rssurl'), table_name='rss_info')
    op.drop_index(op.f('ix_rss_info_userid'), table_name='rss_info')
    op.alter_column('subscription', 'price',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('subscription', 'reminder_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('subscription', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('subscription', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('subscription', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.drop_index(op.f('ix_subscription_createdat'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_userid'), table_name='subscription')
    op.alter_column('user', 'github_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user', 'password_hash',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('user', 'last_login_ip',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('user', 'current_login_ip',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('user', 'login_count',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('user', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_user_deletedat'), table_name='user')
    op.drop_column('user', 'deleted_at')
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_user_deletedat'), 'user', ['deleted_at'], unique=False)
    op.alter_column('user', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('user', 'login_count',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('user', 'current_login_ip',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user', 'last_login_ip',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user', 'password_hash',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('user', 'github_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.create_index(op.f('ix_subscription_userid'), 'subscription', ['user_id'], unique=False)
    op.create_index(op.f('ix_subscription_createdat'), 'subscription', ['created_at'], unique=False)
    op.alter_column('subscription', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('subscription', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('subscription', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('subscription', 'reminder_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('subscription', 'price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.create_index(op.f('ix_rss_info_userid'), 'rss_info', ['user_id'], unique=False)
    op.create_index(op.f('ix_rss_info_rssurl'), 'rss_info', ['rss_url'], unique=False)
    op.create_index(op.f('ix_rss_info_createdat'), 'rss_info', ['created_at'], unique=False)
    op.alter_column('rss_info', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('rss_info', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('rss_info', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('rss_info', 'entry_count',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('rss_info', 'rss_url',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_constraint(op.f('uq_profile_user_id'), 'profile', type_='unique')
    op.create_index(op.f('ix_profile_userid'), 'profile', ['user_id'], unique=True)
    op.alter_column('profile', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.add_column('passkey_credential', sa.Column('backup_eligible', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('passkey_credential', sa.Column('backup_state', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('passkey_credential', sa.Column('attestation_format', sa.VARCHAR(length=50), server_default=sa.text("'none'::character varying"), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_passkey_credential_userid'), 'passkey_credential', ['user_id'], unique=False)
    op.create_index(op.f('ix_passkey_credential_createdat'), 'passkey_credential', ['created_at'], unique=False)
    op.alter_column('passkey_credential', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('passkey_credential', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('passkey_credential', 'sign_count',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('passkey_credential', 'public_key',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('passkey_credential', 'credential_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('log', 'extra',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('log', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('log', 'level',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('log', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_gallery_image_status'), table_name='gallery_image')
    op.create_index(op.f('ix_gallery_image_userid'), 'gallery_image', ['user_id'], unique=False)
    op.create_index(op.f('ix_gallery_image_sortorder'), 'gallery_image', ['sort_order'], unique=False)
    op.create_index(op.f('ix_gallery_image_createdat'), 'gallery_image', ['created_at'], unique=False)
    op.alter_column('gallery_image', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('gallery_image', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('gallery_image', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('gallery_image', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('gallery_image', 'exif',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('gallery_image', 'sort_order',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('gallery_image', 'description',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('gallery_image', 'mime_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'image/jpeg'::character varying"))
    op.alter_column('gallery_image', 'file_size',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('gallery_image', 'status')
    op.drop_column('gallery_image', 'aspect_ratio')
    op.drop_column('gallery_image', 'height')
    op.drop_column('gallery_image', 'width')
    op.drop_column('gallery_image', 'medium_url')
    op.drop_column('gallery_image', 'thumbnail_url')
    op.alter_column('event', 'extra',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('event', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('event', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('event', 'source',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('event', 'type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('event', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_device_track_userid'), 'device_track', ['user_id'], unique=False)
    op.create_index(op.f('ix_device_track_createdat'), 'device_track', ['created_at'], unique=False)
    op.alter_column('device_track', 'reminder_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('device_track', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('device_track', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('device_track', 'price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               nullable=True)
    op.alter_column('device_track', 'purchase_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('device_track', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('device_track', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.create_table('subscriptions',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('billing_cycle', postgresql.ENUM('monthly', 'quarterly', 'yearly', name='billing_cycle_enum'), autoincrement=False, nullable=False),
    sa.Column('next_billing_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('active', 'canceled', 'paused', 'expired', name='subscription_status_enum'), autoincrement=False, nullable=False),
    sa.Column('reminder_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('subscriptions_pkey'))
    )
    op.create_index(op.f('ix_subscriptions_userid'), 'subscriptions', ['user_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_createdat'), 'subscriptions', ['created_at'], unique=False)
    op.create_table('gallery_images',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True),
    sa.Column('file_size', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('mime_type', sa.VARCHAR(length=50), server_default=sa.text("'image/jpeg'::character varying"), autoincrement=False, nullable=True),
    sa.Column('sort_order', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('exif', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('gallery_images_pkey'))
    )
    op.create_index(op.f('ix_gallery_images_userid'), 'gallery_images', ['user_id'], unique=False)
    op.create_index(op.f('ix_gallery_images_sortorder'), 'gallery_images', ['sort_order'], unique=False)
    op.create_index(op.f('ix_gallery_images_createdat'), 'gallery_images', ['created_at'], unique=False)
    op.create_table('logs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('level', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('logs_pkey'))
    )
    op.create_index(op.f('ix_logs_timestamp'), 'logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_logs_level'), 'logs', ['level'], unique=False)
    op.create_index(op.f('ix_logs_id'), 'logs', ['id'], unique=False)
    op.create_table('device_tracks',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('purchase_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('active', 'retired', name='device_status_enum'), autoincrement=False, nullable=False),
    sa.Column('reminder_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('device_tracks_pkey'))
    )
    op.create_index(op.f('ix_device_tracks_userid'), 'device_tracks', ['user_id'], unique=False)
    op.create_index(op.f('ix_device_tracks_createdat'), 'device_tracks', ['created_at'], unique=False)
    op.create_table('rss_infos',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('rss_url', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('feed_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('feed_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('feed_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('feed_published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('entry_count', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('last_fetched_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('rss_infos_pkey'))
    )
    op.create_index(op.f('ix_rss_infos_userid'), 'rss_infos', ['user_id'], unique=False)
    op.create_index(op.f('ix_rss_infos_rssurl'), 'rss_infos', ['rss_url'], unique=False)
    op.create_index(op.f('ix_rss_infos_createdat'), 'rss_infos', ['created_at'], unique=False)
    op.create_table('visitor_tracks',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('visitor_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('page_url', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('page_path', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('referrer', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('browser', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('screen_resolution', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('visit_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('browser_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('browser_version', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('os_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('os_version', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('cpu', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('device_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('visitor_tracks_pkey'))
    )
    op.create_index(op.f('ix_visitor_tracks_visittime'), 'visitor_tracks', ['visit_time'], unique=False)
    op.create_index(op.f('ix_visitor_tracks_visitorid'), 'visitor_tracks', ['visitor_id'], unique=False)
    op.create_index(op.f('ix_visitor_tracks_ipaddress'), 'visitor_tracks', ['ip_address'], unique=False)
    op.create_table('passkey_credentials',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('credential_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('public_key', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('sign_count', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('passkey_credentials_pkey')),
    sa.UniqueConstraint('credential_id', name=op.f('uq_passkey_credentials_credential_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_passkey_credentials_userid'), 'passkey_credentials', ['user_id'], unique=False)
    op.create_index(op.f('ix_passkey_credentials_createdat'), 'passkey_credentials', ['created_at'], unique=False)
    op.create_table('visitor_track',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('visitor_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('page_url', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('page_path', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('referrer', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('browser', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('screen_resolution', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('visit_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('browser_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('browser_version', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('os_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('os_version', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('cpu', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('device_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visitor_track'))
    )
    op.create_index(op.f('ix_visitor_track_visittime'), 'visitor_track', ['visit_time'], unique=False)
    op.create_index(op.f('ix_visitor_track_visitorid'), 'visitor_track', ['visitor_id'], unique=False)
    op.create_index(op.f('ix_visitor_track_visitor_id'), 'visitor_track', ['visitor_id'], unique=False)
    op.create_index(op.f('ix_visitor_track_visit_time'), 'visitor_track', ['visit_time'], unique=False)
    op.create_index(op.f('ix_visitor_track_ipaddress'), 'visitor_track', ['ip_address'], unique=False)
    op.create_index(op.f('ix_visitor_track_ip_address'), 'visitor_track', ['ip_address'], unique=False)
    op.create_index(op.f('idx_visit_time_visitor_id'), 'visitor_track', ['visit_time', 'visitor_id'], unique=False)
    op.create_index(op.f('idx_visit_time_page_path'), 'visitor_track', ['visit_time', 'page_path'], unique=False)
    op.create_index(op.f('idx_visit_time_ip_address'), 'visitor_track', ['visit_time', 'ip_address'], unique=False)
    op.create_index(op.f('idx_visit_time_device_type'), 'visitor_track', ['visit_time', 'device_type'], unique=False)
    op.create_index(op.f('idx_visit_os_stats'), 'visitor_track', ['visit_time', 'os_name', 'os_version'], unique=False)
    op.create_index(op.f('idx_visit_browser_stats'), 'visitor_track', ['visit_time', 'browser_name', 'browser_version'], unique=False)
    op.create_table('category',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category')),
    sa.UniqueConstraint('name', name=op.f('uq_category_name'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
